name: Build and push python image to GCP
on:
  push:
    branches:
      - main

jobs:
  build-push-gcr:
    name: Build and push Docker image to Google Cloud Registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: get_health_fastapi
      PROJECT_ID: mycicdproject-426810
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build the Docker image
        run: |
            docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker client
        run: |
            gcloud auth configure-docker --quiet
            gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

      - name: Push the Docker image to Google Cloud Registry
        env:
          GIT_TAG: v0.1.0
        run: |
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: Push the Docker image to Artifact Registry
        env:
          GIT_TAG: v0.1.0
          ARTIFACT_REG: asia-southeast2-docker.pkg.dev
        run: |
          docker tag $IMAGE_NAME:latest $ARTIFACT_REG/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
          docker tag $IMAGE_NAME:latest $ARTIFACT_REG/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push $ARTIFACT_REG/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
          docker push $ARTIFACT_REG/$PROJECT_ID/images/$IMAGE_NAME:latest
